### PR TITLE
my first changes in frontend

### PR DESCRIPTION
**Pull request by Maryamh12**

### CODE REVIEW

**Review by Joshf225 — APPROVED** [review]
this looks good, great job! Although you made these changes in the directory we are not working on anymore and is now deleted, but ill try my best to add your changes to our working directory. Great job!

**Comment by Maryamh12** [comment]
I didn't know that we don't work on the dev-Branch anymore. Could you please clarify where I should merge these changes? Should they be merged into the main branch? Thanks for the heads-up!

**Comment by Joshf225** [comment]
I have closed this and re made a new merge request /PR, you can see the changes i added there if youd like and then please approve the merge

**Comment by Maryamh12** [comment]
Thank you for the update. Since the merge has already been completed, there is no active pull request for me to approve. I trust that you have reviewed the changes and ensured everything is in order. Please confirm if any further action is needed on my part.

**Comment by Joshf225** [comment]
No thats it , someone else ended up approving it for me, although i was wondering since we are all now updated and noe working of the dev branch can i delete your branch ?

**Comment by Maryamh12** [comment]
I wasn't able to review and approve the new merge because I wasn't selected for it, and as a result, I didn't see anything in my Git to approve. Currently, I have ongoing work on the basket page and responsive design locally in this branch, which still requires my attention. I pushed my first changes in frontend because  I only want to push the progress up to this part in github that  maby you need it for verfiying the endpoints in backend. please give me some more time to work on this branch? I still need it for my ongoing work. Once I've completed and integrated my changes, we can remove it.

**Comment by Joshf225** [comment]
thats fine with mari

**Pull request closed without merging**
